### PR TITLE
Add targets to Carthage

### PR DESCRIPTION
**Pull request by AlbGarciam**
Carthage was only building Inject module. With this PR it'll build the following targets:
* Inject
* Keychain
* Singleton
* Storage
* UserDefault

---
This change is [Reviewable](https://reviewable.io/reviews/alexruperez/securepropertystorage/19)

### CODE REVIEW

**Comment by alexruperez** [comment]
CI  needs SecurePropertyStorage-Package scheme, I’ll fix it ASAP, changing the workflow or restoring the scheme.

**Comment by AlbGarciam** [comment]
> Running CI, thanks @AlbGarciam! This fix #18?

I used the approach of using Carthage to build the compiled version of the framework and using SPM to build the non-compiled version of the framework. 

It works well on the first integrations I'm doing but I'm still working on verify it. I'll let you know once I finish testing it

**Comment by AlbGarciam** [comment]
> > Running CI, thanks @AlbGarciam! This fix #18?
> 
> I used the approach of using Carthage to build the compiled version of the framework and using SPM to build the non-compiled version of the framework.
> 
> It works well on the first integrations I'm doing but I'm still working on verifying it. I'll let you know once I finish testing it

@alexruperez Seems you cannot import via SPM and make a property wrapper as public. By importing it as a compiled framework the issue is gone

**Comment by alexruperez** [comment]
Declined in favor of #20

**Pull request closed without merging**
